import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { tmpdir } from 'os'
import { execa } from 'execa'
import { resolveTemplatesDir } from './copy-templates.js'

const SCRIPT = join(resolveTemplatesDir(), '.github', 'scripts', 'check-file-sizes.mjs')

const lines = (n: number, prefix = 'const x') => Array.from({ length: n }, (_, i) => `${prefix}${i} = ${i}`).join('\n') + '\n'

let root: string
let repo: string

const git = (...args: string[]) => execa('git', args, { cwd: repo })

function put(rel: string, content: string | Buffer): void {
  mkdirSync(dirname(join(repo, rel)), { recursive: true })
  writeFileSync(join(repo, rel), content)
}

async function commit(files: Record<string, string | Buffer>): Promise<void> {
  for (const [rel, content] of Object.entries(files)) put(rel, content)
  await git('add', '-A')
  await git('commit', '-q', '--allow-empty', '-m', 'change')
}

// GITHUB_BASE_REF is blanked so this suite behaves the same when goodvibes' own CI runs it on a pull request.
async function check(env: Record<string, string> = {}) {
  const r = await execa('node', [SCRIPT], { cwd: repo, reject: false, env: { GITHUB_BASE_REF: '', ...env } })
  return { code: r.exitCode, out: `${r.stdout}\n${r.stderr}` }
}

beforeEach(async () => {
  root = mkdtempSync(join(tmpdir(), 'gv-file-size-'))
  repo = join(root, 'repo')
  mkdirSync(repo)
  await git('init', '-q', '-b', 'main')
  await git('config', 'user.email', 'test@example.com')
  await git('config', 'user.name', 'Test')
  await git('config', 'commit.gpgsign', 'false')
})

afterEach(() => {
  rmSync(root, { recursive: true, force: true })
})

describe('check-file-sizes against the previous commit', () => {
  it('passes a new file at or under the limit', async () => {
    await commit({ 'README.md': 'hi\n' })
    await commit({ 'src/a.ts': lines(500) })
    expect((await check()).code).toBe(0)
  })

  it('fails a new file over the limit and says how to raise the limit', async () => {
    await commit({ 'README.md': 'hi\n' })
    await commit({ 'src/big.ts': lines(501) })
    const { code, out } = await check()
    expect(code).toBe(1)
    expect(out).toContain('src/big.ts: 501 lines (limit 500). Split it into smaller files')
    expect(out).toContain('.github/file-size-limits.json')
    expect(out).toContain('"src/big.ts": 501')
  })

  it('fails an existing over-limit file that grows', async () => {
    await commit({ 'src/big.py': lines(900, 'x') })
    await commit({ 'src/big.py': lines(950, 'x') })
    const { code, out } = await check()
    expect(code).toBe(1)
    expect(out).toContain(
      'src/big.py: grew from 900 to 950 lines; it is already over the 500-line limit, so it may not grow. Move new code into a new file.',
    )
  })

  it('passes an existing over-limit file that shrinks or is left alone', async () => {
    await commit({ 'src/big.go': lines(900), 'src/old.go': lines(700) })
    await commit({ 'src/big.go': lines(850), 'src/small.go': lines(10) })
    expect((await check()).code).toBe(0)
  })

  it('fails a file that crosses the limit in this change', async () => {
    await commit({ 'src/a.rs': lines(480) })
    await commit({ 'src/a.rs': lines(520) })
    const { code, out } = await check()
    expect(code).toBe(1)
    expect(out).toContain('src/a.rs: 520 lines (limit 500).')
  })

  it('follows a rename, so a renamed over-limit file still may not grow', async () => {
    await commit({ 'src/old.ts': lines(900) })
    await git('mv', 'src/old.ts', 'src/new.ts')
    await commit({ 'src/new.ts': lines(901) })
    const { code, out } = await check()
    expect(code).toBe(1)
    expect(out).toContain('src/new.ts: grew from 900 to 901 lines')
  })

  it('ignores deleted files and text files that are not code', async () => {
    await commit({ 'src/gone.ts': lines(10) })
    await git('rm', '-q', 'src/gone.ts')
    await commit({ 'docs/guide.md': lines(3000), 'data.json': lines(3000) })
    expect((await check()).code).toBe(0)
  })

  it('skips lockfiles, minified, dist, build, node_modules, vendor, .venv, generated and binary files', async () => {
    await commit({ 'README.md': 'hi\n' })
    const big = lines(900)
    await commit({
      'dist/app.js': big,
      'web/build/app.js': big,
      'node_modules/pkg/index.js': big,
      'vendor/lib.go': big,
      '.venv/lib/site.py': big,
      'public/app.min.js': big,
      'yarn.lock': big,
      'pnpm-lock.yaml': big,
      'src/api.pb.go': `// Code generated by protoc. DO NOT EDIT.\n${big}`,
      'src/schema.ts': `/**\n * this file is\n * @generated\n */\n${big}`,
      'src/blob.ts': Buffer.concat([Buffer.from([0, 1, 2]), Buffer.from(big)]),
    })
    const { code, out } = await check()
    expect(out).toContain('File size check passed: 0 code files checked')
    expect(code).toBe(0)
  })

  it('does not skip a generated marker below the first five lines', async () => {
    await commit({ 'README.md': 'hi\n' })
    await commit({ 'src/late.ts': `${lines(5)}// @generated\n${lines(600)}` })
    expect((await check()).code).toBe(1)
  })
})

describe('check-file-sizes config file', () => {
  it('applies default and per-extension limits, including extensions that are not code by default', async () => {
    await commit({ '.github/file-size-limits.json': JSON.stringify({ default: 100, extensions: { '.py': 600, '.md': 10 } }) })
    await commit({ 'a.py': lines(550), 'b.ts': lines(101), 'c.md': lines(11) })
    const { code, out } = await check()
    expect(code).toBe(1)
    expect(out).not.toContain('a.py')
    expect(out).toContain('b.ts: 101 lines (limit 100).')
    expect(out).toContain('c.md: 11 lines (limit 10).')
  })

  it('lets one file have its own limit through allow', async () => {
    await commit({ '.github/file-size-limits.json': JSON.stringify({ allow: { 'src/big.ts': 1000 } }) })
    await commit({ 'src/big.ts': lines(1000) })
    expect((await check()).code).toBe(0)
    await commit({ 'src/big.ts': lines(1001) })
    const { code, out } = await check()
    expect(code).toBe(1)
    expect(out).toContain('src/big.ts: 1001 lines (limit 1000).')
  })

  it('skips paths matching ignore globs with *, ** and ?', async () => {
    await commit({ '.github/file-size-limits.json': JSON.stringify({ ignore: ['gen/**', '**/*.fixture.ts', 'src/t?.ts'] }) })
    await commit({
      'gen/deep/a.ts': lines(900),
      'test/x/y.fixture.ts': lines(900),
      'src/t1.ts': lines(900),
      'src/t10.ts': lines(900),
    })
    const { code, out } = await check()
    expect(code).toBe(1)
    expect(out).toContain('src/t10.ts: 900 lines')
    expect(out).not.toContain('gen/deep/a.ts')
    expect(out).not.toContain('y.fixture.ts')
    expect(out).not.toContain('src/t1.ts')
  })

  it('fails loudly on an unknown config key instead of ignoring it', async () => {
    await commit({ '.github/file-size-limits.json': JSON.stringify({ allowed: { 'a.ts': 900 } }) })
    const { code, out } = await check()
    expect(code).toBe(1)
    expect(out).toContain('unknown key "allowed"')
  })
})

describe('check-file-sizes base selection', () => {
  it('passes a first commit whose files are all under the limit', async () => {
    await commit({ 'src/ok.ts': lines(400), 'docs/long.md': lines(900) })
    const { code, out } = await check()
    expect(out).toContain('File size check passed: 1 code file checked')
    expect(code).toBe(0)
  })

  it('checks every file as new when there is no previous commit', async () => {
    await commit({ 'src/big.ts': lines(501) })
    const { code, out } = await check()
    expect(code).toBe(1)
    expect(out).toContain('src/big.ts: 501 lines (limit 500).')
  })

  it('compares a pull request with origin/<base>, not the local base branch or the previous commit', async () => {
    const remote = join(root, 'remote.git')
    await execa('git', ['init', '-q', '--bare', remote])
    await commit({ 'README.md': 'hi\n' })
    await git('remote', 'add', 'origin', remote)
    await git('push', '-q', 'origin', 'main')
    await commit({ 'src/big.ts': lines(600) })
    await git('checkout', '-q', '-b', 'feature')
    await commit({ 'src/small.ts': lines(10) })

    expect((await check()).code).toBe(0)
    const { code, out } = await check({ GITHUB_BASE_REF: 'main' })
    expect(code).toBe(1)
    expect(out).toContain('src/big.ts: 600 lines (limit 500).')
  })

  it('explains full history is needed when origin/<base> is missing', async () => {
    await commit({ 'README.md': 'hi\n' })
    const { code, out } = await check({ GITHUB_BASE_REF: 'main' })
    expect(code).toBe(1)
    expect(out).toContain('origin/main')
    expect(out).toContain('fetch-depth: 0')
  })
})
