name = "goodvibes-telemetry"
main = "worker.js"
compatibility_date = "2025-01-01"
workers_dev = true

[[kv_namespaces]]
binding = "INSTALLS"
# created via: wrangler kv namespace create INSTALLS
id = "b8a19ad579f343a794771d7809486f7a"
